[package]
name = "rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"
authors = ["John Campbell <johncampbell@geospatialweb.ca> <http://www.linkedin.com/in/geospatialweb>"]
repository = "https://gitlab.com/geospatialweb/rust-vue3-tsx"
homepage = "https://www.geospatialweb.ca/"
license = "MIT"
publish = false

[dependencies]
dotenvy = "0.15.7"
envy = "0.4.2"
salvo = "0.60"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }

[lib]
name = "lib"
path="src/lib/lib.rs"
