[package]
name = "rust_mvt_postgis"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"
authors = ["John Campbell <johncampbell@geospatialweb.ca> <http://www.linkedin.com/in/geospatialweb>"]
repository = "https://gitlab.com/geospatialweb/rust-mvt-postgis"
homepage = "https://www.geospatialweb.ca/"
license = "MIT"
publish = false

[dependencies]
chrono = "0.4"
dotenvy = "0.15"
envy = "0.4"
garde = "0.16"
geojson = "0.24"
jsonwebtoken = "9"
once_cell = "1"
salvo = { version = "0.63", features = ["cors", "jwt-auth", "logging", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[lib]
name = "lib"
path="src/lib/mod.rs"
