build:
	@cargo build --bin main

check:
	@cargo check

clippy:
	@cargo clippy

docker:
	@docker compose up -d

release:
	@cargo build --bin main --release

run:
	@cargo run --bin main

test:
	@cargo test --lib -- --test-threads=1

update:
	@cargo update --verbose

upgrade:
	@rustup update stable
